accessControl:
  autologinAs: guest
  autologinLocal: true
  localNetworks:
  - 10.0.0.0/16
  salt: ofveZnTRKgyNjzo6nZexEpi5y7xzQJ5Q
api:
  key: 587186F55E6A41A78A06B038C2E681C8
appearance:
  color: red
  name: Space Taz 5
events:
  subscriptions:
  - command: 'youtube-upload --client-secrets=/home/pi/client-secrets-youtube-upload.json
      --title="Timelapse: {gcode}" --playlist="3D printing timelapses" --description="Timelapse
      of {gcode}, printed on space-taz5@HSBNE by Octoprint" --tags="reprap,timelapse,octoprint,hsbne,taz5"
      "{movie}"'
    debug: false
    event: MovieDone
    type: system
  - command: wget -O /dev/null http://themes.hsbne.org/playmp3.php?nickname=space-taz5
    debug: false
    event: PrintDone
    type: system
feature:
  sdSupport: false
gcodeViewer: {}
plugins:
  announcements:
    channels:
      _important:
        read_until: 1460575175
  cost:
    cost_per_hour: '0.5'
    cost_per_meter: '0.5'
    currency: AUD$
  cura:
    cura_engine: /usr/local/bin/cura_engine
  discovery:
    publicPort: 80
    upnpUuid: 1699e2f0-c433-44fd-9846-dabe8c92c6f8
  slack:
    _config_version: 3
    bot_icon_emoji: ':printer:'
    bot_username: space-taz5
    print_events:
      PrintFailed:
        Enabled: false
    webhook_url: https://hooks.slack.com/services/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
  softwareupdate:
    _config_version: 4
    checks:
      octoprint:
        checkout_folder: /home/pi/OctoPrint
        type: github_release
printerParameters: {}
printerProfiles:
  defaultProfile:
    axes:
      e:
        inverted: false
        speed: 300
      x:
        inverted: false
        speed: 6000
      y:
        inverted: false
        speed: 6000
      z:
        inverted: false
        speed: 200
    color: red
    extruder:
      count: 1
      nozzleDiameter: 0.5
      offsets:
      - - 0.0
        - 0.0
    heatedBed: true
    id: _default
    model: Lulzbot Taz 5
    name: Default
    volume:
      depth: 275.0
      formFactor: rectangular
      height: 250.0
      origin: lowerleft
      width: 290.0
serial:
  autoconnect: true
  baudrate: 115200
  maxCommunicationTimeouts: {}
  port: /dev/ttyACM0
  timeout: {}
server:
  commands:
    serverRestartCommand: sudo service octoprint restart
    systemRestartCommand: sudo shutdown -r now
  firstRun: false
  secretKey: tn9hOOfKqptjJv6x23M5BXgflxrDwAN7
slicing:
  defaultProfiles:
    cura: abs_high-speed
system:
  actions:
  - action: shutdown
    async: true
    command: sudo shutdown -h now
    confirm: You are about to shutdown the system.
    ignore: true
    name: Shutdown
  - action: reboot
    async: true
    command: sudo shutdown -r now
    confirm: You are about to reboot the system
    ignore: true
    name: Reboot
  - action: restart
    async: true
    command: sudo service octoprint restart
    confirm: You are about to restart OctoPrint
    ignore: true
    name: Restart OctoPrint
temperature:
  profiles:
  - bed: 100
    extruder: 210
    name: ABS
  - bed: 60
    extruder: 180
    name: PLA
  - bed: '85'
    extruder: '235'
    name: nGen
webcam:
  ffmpeg: /home/pi/.octoprint/scripts/ffmpeg-gpu.pl
  snapshot: http://127.0.0.1:8080/?action=snapshot
  stream: /webcam/?action=stream
  timelapse:
    fps: 25
    options:
      interval: 10
    postRoll: 0
    type: timed
  watermark: false
